### ISSUE TITLE
Non deterministic render test failures

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/carto-vl#337]
We've seen a few times now some MGL-integration tests fail randomly on `master` since this is very difficult to reproduce, we should improve the testing framework to show more information. Not just a pixel mismatch.

For example:

- Console errors, console warns
- Uncaught exceptions
- Time, did it timeout?

**Comment by davidmanzanares** [comment]
The lack of good error messages is also a problem when modifying the testing code. For example, while fixing the `e2e` tests I get this error:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Error: Event
    at Page._handleException (/home/dv/github/renderer-prototype/node_modules/puppeteer/lib/Page.js:427:38)
    at CDPSession.Page.client.on.exception (/home/dv/github/renderer-prototype/node_modules/puppeteer/lib/Page.js:103:60)
    at CDPSession.emit (events.js:127:13)
    at CDPSession._onMessage (/home/dv/github/renderer-prototype/node_modules/puppeteer/lib/Connection.js:219:12)
    at Connection._onMessage (/home/dv/github/renderer-prototype/node_modules/puppeteer/lib/Connection.js:119:19)
    at WebSocket.emit (events.js:127:13)
    at Receiver._receiver.onmessage (/home/dv/github/renderer-prototype/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/home/dv/github/renderer-prototype/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/dv/github/renderer-prototype/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/dv/github/renderer-prototype/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/dv/github/renderer-prototype/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/home/dv/github/renderer-prototype/node_modules/ws/lib/WebSocket.js:138:22)
    at Socket.emit (events.js:127:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:598:20)
```
I know that some URLs must be incorrect, but I don't receive information about which one

**Comment by davidmanzanares** [comment]
Finally, I managed to fix my URL problem, but I had to disable the "headless" option and, more importantly, hack `exquisite` to don't close the browser window after errors.

**Comment by IagoLast** [comment]
Raul added a `pageEvents` option functionality to catch [page events](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-page) using exquisite API, I created a demo test showing how to manage network errors [here](https://github.com/IagoLast/Exquisite/blob/337-improve-logs/test/index.test.js#L85)

Maybe we can update the [testSST](https://github.com/CartoDB/carto-vl/blob/master/test/common/util.js#L53) function and add reactions to those events.

**Comment by IagoLast** [comment]
- https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-error
- https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-pageerror
- https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-requestfailed

**Comment by davidmanzanares** [comment]
I understand that the logging on the tests has been changed to increase verbosity and that we are waiting to see another random test failure.

Marking as `blocked`.

**Comment by davidmanzanares** [comment]
Another failure: https://circleci.com/gh/CartoDB/carto-vl/6456

It was "fixed" by a re-run, so the problem is non-deterministic. The log didn't provide good information.

**Comment by davidmanzanares** [comment]
Related.

Please, no more errors like these:
```
Taking reference from /sprites/no-override
Request {
  _client: 
   CDPSession {
     domain: null,
     _events: 
      { 'Page.frameAttached': [Function],
        'Page.frameNavigated': [Function],
        'Page.navigatedWithinDocument': [Function],
        'Page.frameDetached': [Function],
        'Page.frameStoppedLoading': [Function],
        'Runtime.executionContextCreated': [Function],
        'Runtime.executionContextDestroyed': [Function],
        'Runtime.executionContextsCleared': [Function],
        'Page.lifecycleEvent': [Function],
        'Network.requestWillBeSent': [Function: bound _onRequestWillBeSent],
        'Network.requestIntercepted': [Function: bound _onRequestIntercepted],
        'Network.requestServedFromCache': [Function: bound _onRequestServedFromCache],
        'Network.responseReceived': [Function: bound _onResponseReceived],
        'Network.loadingFinished': [Function: bound _onLoadingFinished],
        'Network.loadingFailed': [Function: bound _onLoadingFailed],
        'Page.domContentEventFired': [Function],
        'Page.loadEventFired': [Function],
        'Runtime.consoleAPICalled': [Function],
        'Page.javascriptDialogOpening': [Function],
        'Runtime.exceptionThrown': [Function],
        'Security.certificateError': [Function],
        'Inspector.targetCrashed': [Function],
        'Performance.metrics': [Function],
        'Log.entryAdded': [Function] },
     _eventsCount: 24,
     _maxListeners: undefined,
     _lastId: 13,
     _callbacks: Map { 13 => [Object] },
     _connection: 
      Connection {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _url: 'ws://127.0.0.1:37601/devtools/browser/548c77f7-8886-4cba-9d36-8291c8716dca',
        _lastId: 16,
        _callbacks: Map {},
        _delay: 0,
        _transport: [WebSocket],
        _sessions: [Map],
        _closeCallback: [Function] },
     _targetId: '4D2220A7304A5F85B3C29A4CB8C12618',
     _sessionId: '4D2220A7304A5F85B3C29A4CB8C12618:1' },
  _requestId: '19F7E2A65805F382ACAC2893382F049D',
  _interceptionId: null,
  _allowInterception: false,
  _interceptionHandled: false,
  _response: null,
  _failureText: 'net::ERR_CONNECTION_REFUSED',
  _url: 'http://localhost:5000/test/integration/render/scenarios/sprites/no-override//scenario.html',
  _resourceType: 'document',
  _method: 'GET',
  _postData: undefined,
  _headers: 
   { 'upgrade-insecure-requests': '1',
     'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/68.0.3419.0 Safari/537.36',
     'x-devtools-emulate-network-conditions-client-id': '4D2220A7304A5F85B3C29A4CB8C12618' },
  _frame: 
   Frame {
     _client: 
      CDPSession {
        domain: null,
        _events: [Object],
        _eventsCount: 24,
        _maxListeners: undefined,
        _lastId: 13,
        _callbacks: [Map],
        _connection: [Connection],
        _targetId: '4D2220A7304A5F85B3C29A4CB8C12618',
        _sessionId: '4D2220A7304A5F85B3C29A4CB8C12618:1' },
     _page: 
      Page {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _client: [CDPSession],
        _target: [Target],
        _keyboard: [Keyboard],
        _mouse: [Mouse],
        _touchscreen: [Touchscreen],
        _frameManager: [FrameManager],
        _networkManager: [NetworkManager],
        _emulationManager: [EmulationManager],
        _tracing: [Tracing],
        _pageBindings: Map {},
        _ignoreHTTPSErrors: false,
        _coverage: [Coverage],
        _defaultNavigationTimeout: 30000,
        _screenshotTaskQueue: [TaskQueue],
        _viewport: [Object] },
     _parentFrame: null,
     _url: 'about:blank',
     _id: '4D2220A7304A5F85B3C29A4CB8C12618',
     _documentPromise: null,
     _contextPromise: Promise { [ExecutionContext] },
     _contextResolveCallback: null,
     _waitTasks: Set {},
     _loaderId: '',
     _lifecycleEvents: 
      Set {
        'commit',
        'DOMContentLoaded',
        'load',
        'networkAlmostIdle',
        'networkIdle' },
     _childFrames: Set {},
     _name: undefined,
     _navigationURL: 'about:blank' },
  _redirectChain: [],
  _fromMemoryCache: false }
(node:2299) UnhandledPromiseRejectionWarning: Error: Error: net::ERR_CONNECTION_REFUSED at http://localhost:5000/test/integration/render/scenarios/sprites/no-override//scenario.html
    at /home/dmanzanares/github/renderer-prototype/node_modules/exquisite-sst/src/exquisite.js:60:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:2299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 2.22s.
```

:cry:

**Comment by IagoLast** [comment]
this is a trace of a refused connection, what do you want to see there instead? just the error name?

**Comment by davidmanzanares** [comment]
Since you asked me, in my dreams I would see the HTTP error code with the URL and the initiator, without the noise.

But I understand that removing noise can be at the same time the opposite of what we want to do with non-deterministic tests. However, the idea is similar: provide good descriptive errors.

**Comment by davidmanzanares** [comment]
It happened again: https://circleci.com/gh/CartoDB/carto-vl/7380

**Comment by davidmanzanares** [comment]
I tried to debug this by using ` while yarn test:render; do echo another one; done;` with a ~hacked~ patched exquisite-sst, but the tests always pass :slightly_frowning_face:

**Comment by davidmanzanares** [comment]
Seems like that script finally stopped with:

```
  66 passing (1m)
  1 failing

  1) Render tests:
       /sprites/builtin:
     Error: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
      at /home/dv/github/renderer-prototype/node_modules/exquisite-sst/src/exquisite.js:60:15
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:118:7)
```

Not very useful information.
