### ISSUE TITLE
Using opacity with a variable isn't working

### ISSUE THREAD

**Issue by makella** [CartoDB/carto-vl#843]
For example:

```
@waiting: ramp(linear($avg_waiting_time,globalMIN($avg_waiting_time),globalMAX($avg_waiting_time)),temps)

width: sqrt($avg_waiting_time)
color: opacity(@waiting,0.8)

```
The reason I don't want to put the opacity in the variable is because I want to vary the opacity for the `strokeWidth` but using the same colors as the fill

Error from the Editor:
```
Invalid viz: Error: opacity(): invalid first parameter 'color'
expected type was 'color', actual type was 'undefined':Error: opacity(): invalid first parameter 'color'
expected type was 'color', actual type was 'undefined'
    at throwInvalidType (https://cartodb.github.io/carto-vl/dist/carto-vl.js:21102:11)
    at checkType (https://cartodb.github.io/carto-vl/dist/carto-vl.js:21173:9)
    at checkLooseType (https://cartodb.github.io/carto-vl/dist/carto-vl.js:21136:9)
    at new Opacity (https://cartodb.github.io/carto-vl/dist/carto-vl.js:19102:70)
    at Object.opacity (https://cartodb.github.io/carto-vl/dist/carto-vl.js:13986:30)
    at parseFunctionCall (https://cartodb.github.io/carto-vl/dist/carto-vl.js:21603:40)
    at parseNode (https://cartodb.github.io/carto-vl/dist/carto-vl.js:21679:16)
    at parseVizNamedExpr (https://cartodb.github.io/carto-vl/dist/carto-vl.js:21589:23)
    at ast.body.map.node (https://cartodb.github.io/carto-vl/dist/carto-vl.js:21564:30)
    at Array.map (<anonymous>)
```

Other than redefining the styling with the other opacity level, it doesn't seem like there is much I can do to not be so repetitive:

```
@waiting_fill: opacity(ramp(linear($avg_waiting_time,globalMIN($avg_waiting_time),globalMAX($avg_waiting_time)),temps),0.8)
@waiting_line: opacity(ramp(linear($avg_waiting_time,globalMIN($avg_waiting_time),globalMAX($avg_waiting_time)),temps),1)


width: sqrt($avg_waiting_time)
color: @waiting_fill
strokeWidth: 1
strokeColor: @waiting_line
```

**Comment by davidmanzanares** [comment]
Fixed by #917
